name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint and Format Check
      run: |
        ./node_modules/.bin/eslint . --ext .ts,.html
        ./node_modules/.bin/prettier --check "src/**/*.{ts,html,scss,json}"

    - name: Build
      run: npm run build --configuration=production

    - name: Archive production artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd dist
        zip -r ../release.zip .

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files:
          - release.zip

    - name: Create artifact for pull requests
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1